name: Deploy to IONOS

on:
  push:
    branches:
      - main  # Cambia "main" si usas otra rama para producción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Usa la versión que corresponde a tu proyecto

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        ftp-server: ftp://huesocabra.com  # Reemplaza con el host FTP de tu servidor
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: build
        server-dir: /  # Si deseas subir el contenido al directorio raíz del dominio
